# Generated by Django 6.0.3 on 2026-03-07 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TraitementImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('date_traitement', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('bande_1', models.ImageField(upload_to='sat/red')),
                ('bande_2', models.ImageField(upload_to='sat/green')),
                ('bande_3', models.ImageField(upload_to='sat/blue')),
                ('bande_4', models.ImageField(upload_to='sat/pir')),
                ('moyen_ndvi', models.FloatField(null=True)),
                ('standard_deviation', models.FloatField(null=True)),
                ('true_color_img', models.ImageField(null=True, upload_to='sat/result/ture/')),
                ('ndvi_img', models.ImageField(null=True, upload_to='sat/result/NDVI/')),
            ],
        ),
    ]
