# Generated by Django 6.0.3 on 2026-03-07 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traitementimage',
            name='class_ndvi',
            field=models.ImageField(null=True, upload_to='sat/result/ture/'),
        ),
        migrations.AddField(
            model_name='traitementimage',
            name='surfaces_clas',
            field=models.JSONField(null=True),
        ),
    ]
