# Generated by Django 6.0.3 on 2026-03-08 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitement', '0002_traitementimage_class_ndvi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparaisonNDVI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_comparaison', models.DateTimeField(auto_now_add=True)),
                ('diff_date', models.FloatField(null=True)),
                ('diff_img', models.ImageField(null=True, upload_to='sat/res/cmp/')),
                ('diff_surface_class', models.JSONField(null=True)),
                ('id_img_ancienne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparaisons_anciennes', to='traitement.traitementimage')),
                ('id_img_recente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparaisons_recente', to='traitement.traitementimage')),
            ],
        ),
    ]
